import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const BHAIAGI_EXPERIMENTAL = truthy("BHAIAGI_EXPERIMENTAL")
const BHAIAGI_DISABLE_CLAUDE_CODE = truthy("BHAIAGI_DISABLE_CLAUDE_CODE")
const BHAIAGI_DISABLE_CLAUDE_CODE_SKILLS =
  BHAIAGI_DISABLE_CLAUDE_CODE || truthy("BHAIAGI_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["BHAIAGI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  BHAIAGI_AUTO_SHARE: truthy("BHAIAGI_AUTO_SHARE"),
  BHAIAGI_AUTO_HEAP_SNAPSHOT: truthy("BHAIAGI_AUTO_HEAP_SNAPSHOT"),
  BHAIAGI_GIT_BASH_PATH: process.env["BHAIAGI_GIT_BASH_PATH"],
  BHAIAGI_CONFIG: process.env["BHAIAGI_CONFIG"],
  BHAIAGI_CONFIG_CONTENT: process.env["BHAIAGI_CONFIG_CONTENT"],
  BHAIAGI_DISABLE_AUTOUPDATE: truthy("BHAIAGI_DISABLE_AUTOUPDATE"),
  BHAIAGI_ALWAYS_NOTIFY_UPDATE: truthy("BHAIAGI_ALWAYS_NOTIFY_UPDATE"),
  BHAIAGI_DISABLE_PRUNE: truthy("BHAIAGI_DISABLE_PRUNE"),
  BHAIAGI_DISABLE_TERMINAL_TITLE: truthy("BHAIAGI_DISABLE_TERMINAL_TITLE"),
  BHAIAGI_SHOW_TTFD: truthy("BHAIAGI_SHOW_TTFD"),
  BHAIAGI_PERMISSION: process.env["BHAIAGI_PERMISSION"],
  BHAIAGI_DISABLE_DEFAULT_PLUGINS: truthy("BHAIAGI_DISABLE_DEFAULT_PLUGINS"),
  BHAIAGI_DISABLE_LSP_DOWNLOAD: truthy("BHAIAGI_DISABLE_LSP_DOWNLOAD"),
  BHAIAGI_ENABLE_EXPERIMENTAL_MODELS: truthy("BHAIAGI_ENABLE_EXPERIMENTAL_MODELS"),
  BHAIAGI_DISABLE_AUTOCOMPACT: truthy("BHAIAGI_DISABLE_AUTOCOMPACT"),
  BHAIAGI_DISABLE_MODELS_FETCH: truthy("BHAIAGI_DISABLE_MODELS_FETCH"),
  BHAIAGI_DISABLE_MOUSE: truthy("BHAIAGI_DISABLE_MOUSE"),
  BHAIAGI_DISABLE_CLAUDE_CODE,
  BHAIAGI_DISABLE_CLAUDE_CODE_PROMPT: BHAIAGI_DISABLE_CLAUDE_CODE || truthy("BHAIAGI_DISABLE_CLAUDE_CODE_PROMPT"),
  BHAIAGI_DISABLE_CLAUDE_CODE_SKILLS,
  BHAIAGI_DISABLE_EXTERNAL_SKILLS: BHAIAGI_DISABLE_CLAUDE_CODE_SKILLS || truthy("BHAIAGI_DISABLE_EXTERNAL_SKILLS"),
  BHAIAGI_FAKE_VCS: process.env["BHAIAGI_FAKE_VCS"],
  BHAIAGI_SERVER_PASSWORD: process.env["BHAIAGI_SERVER_PASSWORD"],
  BHAIAGI_SERVER_USERNAME: process.env["BHAIAGI_SERVER_USERNAME"],
  BHAIAGI_ENABLE_QUESTION_TOOL: truthy("BHAIAGI_ENABLE_QUESTION_TOOL"),

  // Experimental
  BHAIAGI_EXPERIMENTAL,
  BHAIAGI_EXPERIMENTAL_FILEWATCHER: Config.boolean("BHAIAGI_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BHAIAGI_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("BHAIAGI_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BHAIAGI_EXPERIMENTAL_ICON_DISCOVERY: BHAIAGI_EXPERIMENTAL || truthy("BHAIAGI_EXPERIMENTAL_ICON_DISCOVERY"),
  BHAIAGI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("BHAIAGI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  BHAIAGI_ENABLE_EXA: truthy("BHAIAGI_ENABLE_EXA") || BHAIAGI_EXPERIMENTAL || truthy("BHAIAGI_EXPERIMENTAL_EXA"),
  BHAIAGI_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("BHAIAGI_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  BHAIAGI_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("BHAIAGI_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  BHAIAGI_EXPERIMENTAL_OXFMT: BHAIAGI_EXPERIMENTAL || truthy("BHAIAGI_EXPERIMENTAL_OXFMT"),
  BHAIAGI_EXPERIMENTAL_LSP_TY: truthy("BHAIAGI_EXPERIMENTAL_LSP_TY"),
  BHAIAGI_EXPERIMENTAL_LSP_TOOL: BHAIAGI_EXPERIMENTAL || truthy("BHAIAGI_EXPERIMENTAL_LSP_TOOL"),
  BHAIAGI_EXPERIMENTAL_PLAN_MODE: BHAIAGI_EXPERIMENTAL || truthy("BHAIAGI_EXPERIMENTAL_PLAN_MODE"),
  BHAIAGI_EXPERIMENTAL_MARKDOWN: !falsy("BHAIAGI_EXPERIMENTAL_MARKDOWN"),
  BHAIAGI_MODELS_URL: process.env["BHAIAGI_MODELS_URL"],
  BHAIAGI_MODELS_PATH: process.env["BHAIAGI_MODELS_PATH"],
  BHAIAGI_DISABLE_EMBEDDED_WEB_UI: truthy("BHAIAGI_DISABLE_EMBEDDED_WEB_UI"),
  BHAIAGI_DB: process.env["BHAIAGI_DB"],
  BHAIAGI_DISABLE_CHANNEL_DB: truthy("BHAIAGI_DISABLE_CHANNEL_DB"),
  BHAIAGI_SKIP_MIGRATIONS: truthy("BHAIAGI_SKIP_MIGRATIONS"),
  BHAIAGI_STRICT_CONFIG_DEPS: truthy("BHAIAGI_STRICT_CONFIG_DEPS"),

  BHAIAGI_WORKSPACE_ID: process.env["BHAIAGI_WORKSPACE_ID"],
  BHAIAGI_EXPERIMENTAL_HTTPAPI: truthy("BHAIAGI_EXPERIMENTAL_HTTPAPI"),
  BHAIAGI_EXPERIMENTAL_WORKSPACES: BHAIAGI_EXPERIMENTAL || truthy("BHAIAGI_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get BHAIAGI_DISABLE_PROJECT_CONFIG() {
    return truthy("BHAIAGI_DISABLE_PROJECT_CONFIG")
  },
  get BHAIAGI_TUI_CONFIG() {
    return process.env["BHAIAGI_TUI_CONFIG"]
  },
  get BHAIAGI_CONFIG_DIR() {
    return process.env["BHAIAGI_CONFIG_DIR"]
  },
  get BHAIAGI_PURE() {
    return truthy("BHAIAGI_PURE")
  },
  get BHAIAGI_PLUGIN_META_FILE() {
    return process.env["BHAIAGI_PLUGIN_META_FILE"]
  },
  get BHAIAGI_CLIENT() {
    return process.env["BHAIAGI_CLIENT"] ?? "cli"
  },
}
